on:
  release:
    types:
      - published

jobs:

  add-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v2
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
        cat .github/templates/ISSUE_TEMPLATE.md | sed -e "s/{{title}}/$GITHUB_EVENT_TITLE/" | sed -e "s/{{body}}/$GITHUB_EVENT_BODY/" | github-issue create
